from calculadora_do_cidadao.adapters.cpi import AllUrbanCityAverage  # noqa
from calculadora_do_cidadao.adapters.dieese import (  # noqa
    CestaBasica,
    CestaBasicaAracaju,
    CestaBasicaBelem,
    CestaBasicaBeloHorizonte,
    CestaBasicaBoaVista,
    CestaBasicaBrasilia,
    CestaBasicaCampoGrande,
    CestaBasicaCentroOeste,
    CestaBasicaCuiaba,
    CestaBasicaCuritiba,
    CestaBasicaFlorianopolis,
    CestaBasicaFortaleza,
    CestaBasicaGoiania,
    CestaBasicaJoaoPessoa,
    CestaBasicaMacae,
    CestaBasicaMacapa,
    CestaBasicaMaceio,
    CestaBasicaManaus,
    CestaBasicaNatal,
    CestaBasicaNordeste,
    CestaBasicaNorte,
    CestaBasicaPalmas,
    CestaBasicaPortoAlegre,
    CestaBasicaPortoVelho,
    CestaBasicaRecife,
    CestaBasicaRioBranco,
    CestaBasicaRioDeJaneiro,
    CestaBasicaSalvador,
    CestaBasicaSaoLuis,
    CestaBasicaSaoPaulo,
    CestaBasicaSudeste,
    CestaBasicaSul,
    CestaBasicaTeresina,
    CestaBasicaVitoria,
)
from calculadora_do_cidadao.adapters.ibge import Inpc, Ipca, Ipca15, IpcaE  # noqa
from calculadora_do_cidadao.adapters.igpm import Igpm  # noqa
